---
- name: Initialize PostgreSQL database cluster, create application DB, and enable custom service on leader only
  hosts: patroni_nodes
  become: yes
  vars_files:
    - group_vars/all.yml
    - host_vars/{{ inventory_hostname }}.yml

  tasks:
    - name: Fail if run on more than one host
      fail:
        msg: "This playbook must be run with -l <hostname> (single host only)"
      when: ansible_play_hosts | length > 1

    - name: Check if database cluster is already initialized
      stat:
        path: "{{ postgres_base_path }}/{{ postgres_env }}/postgres/{{ postgres_version }}/{{ postgres_db }}/PG_VERSION"
      register: pgdata_initialized

    - name: Initialize PostgreSQL database cluster (initdb) on leader only
      command: "{{ pg_bin_dir }}/initdb -D {{ postgres_base_path }}/{{ postgres_env }}/postgres/{{ postgres_version }}/{{ postgres_db }} --encoding=UTF8 --locale=C"
      become_user: "{{ postgres_user }}"
      when: 
        - my_role == "leader"
        - not pgdata_initialized.stat.exists
      register: initdb_result

    - name: Show initdb result
      debug:
        msg: "{{ initdb_result.stdout | default('Database cluster already initialized') }}"

    - name: Create private sockets directory (to avoid /run permission issues)
      file:
        path: "{{ postgres_base_path }}/{{ postgres_env }}/postgres/{{ postgres_version }}/{{ postgres_db }}/sockets"
        state: directory
        owner: "{{ postgres_user }}"
        group: "{{ postgres_group }}"
        mode: '0700'
      when: my_role == "leader"

    - name: Apply SELinux context to sockets directory
      command: "{{ item }}"
      loop:
        - semanage fcontext -a -t postgresql_db_t "{{ postgres_base_path }}/{{ postgres_env }}/postgres/{{ postgres_version }}/{{ postgres_db }}/sockets(/.*)?"
        - restorecon -Rv "{{ postgres_base_path }}/{{ postgres_env }}/postgres/{{ postgres_version }}/{{ postgres_db }}/sockets"
      changed_when: false
      when: my_role == "leader"

    - name: Set unix_socket_directories to private dir in postgresql.conf
      lineinfile:
        path: "{{ postgres_base_path }}/{{ postgres_env }}/postgres/{{ postgres_version }}/{{ postgres_db }}/postgresql.conf"
        regexp: "^unix_socket_directories\\s*="
        line: "unix_socket_directories = '{{ postgres_base_path }}/{{ postgres_env }}/postgres/{{ postgres_version }}/{{ postgres_db }}/sockets'"
        create: yes
      notify: reload PostgreSQL config
      when: my_role == "leader"

    - name: Enable and start custom PostgreSQL service on leader
      systemd:
        name: "postgresql@{{ postgres_db }}.{{ postgres_port }}"
        enabled: yes
        state: started
        daemon_reload: yes
      when: my_role == "leader"

    - name: Wait for PostgreSQL to accept connections on leader
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ postgres_port }}"
        delay: 5
        timeout: 90
      when: my_role == "leader"

    - name: Create application database {{ postgres_db }} if not exists on leader
      command: >
        {{ pg_bin_dir }}/psql -p {{ postgres_port }} -U {{ postgres_superuser_username }} -d postgres -c 
        "SELECT 1 FROM pg_database WHERE datname = '{{ postgres_db }}'" | grep -q 1 || 
        {{ pg_bin_dir }}/psql -p {{ postgres_port }} -U {{ postgres_superuser_username }} -d postgres -c 
        "CREATE DATABASE {{ postgres_db }} OWNER {{ postgres_user }};"
      become_user: "{{ postgres_user }}"
      when: my_role == "leader"
      register: create_db_result

    - name: Grant privileges on {{ postgres_db }} to functional user on leader
      command: >
        {{ pg_bin_dir }}/psql -p {{ postgres_port }} -U {{ postgres_superuser_username }} -d postgres -c 
        "GRANT ALL PRIVILEGES ON DATABASE {{ postgres_db }} TO {{ postgres_user }};"
      become_user: "{{ postgres_user }}"
      when: my_role == "leader"

    - name: Show database creation result
      debug:
        msg: "{{ create_db_result.stdout | default('Database already exists') }}"

  handlers:
    - name: reload PostgreSQL config
      systemd:
        name: "postgresql@{{ postgres_db }}.{{ postgres_port }}"
        state: reloaded
